mParticle/react-native-mparticle

- android/src/main/java/com/mparticle/react/MParticlePackage.java
- package.json
- sample/android/app/src/main/java/com/mparticlesample/MainApplication.java
- sample/package.json
Breaking change in RN 0.47 requires the removal of all overrides of ‘createJSModules’
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
> Update MParticlePackage.java to support React Native 0.47+

- package.json
- react-native-mparticle.podspec
To be able to integrate react-native-mparticle with existing app using Podfile instead of adding library to xcode project we need react-native-mparticle.podspec
usage example:
```
pod 'react-native-mparticle', :path => '../node_modules/react-native-mparticle/react-native-mparticle.podspec'
```
> Adds react-native-mparticle.podspec

- android/build.gradle
Fix for: 
Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> Fix for: Android Configuration 'provided' is obsolete

- android/src/main/java/com/mparticle/react/MParticleModule.java
👋 Since the @ReactMethod decorator is not present on getSession method, it's not usable on Android environment.
> Add @ReactMethod decorator to getSession method

- ios/RNMParticle/RNMParticle.m
Hi team! 
I've seen that you've implemented [a null check for the session object in Android](https://github.com/mParticle/react-native-mparticle/commit/beb21f1cfae382656388489a8d9b8c5d54ede512) but [it's missing on iOS](https://github.com/mParticle/mparticle-apple-sdk/blob/master/mParticle-Apple-SDK/mParticle.m#L646-L661).
We have seen some crash reports on iOS regarding that so I thought it'd be nice to fix this.
> Implement null check for session on iOS

- ios/RNMParticle/RNMParticle.m
- js/index.js
When trying to set ATT status on a React Native implementation timestamp can not be set as null for casting reasons to Android. Added separate methods for setting with or without a timestamp.
> Fix Nullabity Issue for ATT Timestamp

- js/index.js
This is to correct a casing issue in the SetUserAttribute js method, which caused the following error
`TypeError: null is not an object (evaluating '_reactNative.NativeModules.Mparticle.setUserAttributeArray')`
This was tested locally and confirmed that the corrected casing addressed the issue. 
Closes https://go.mparticle.com/work/64134
> Correct Casing in SetUserAttribute js method

- android/src/main/java/com/mparticle/react/MParticleModule.java
- ios/RNMParticle/RNMParticle.m
- js/index.js
We added the upload bypass option for events (shouldUploadEvent property) in the core iOS and Android SDKs, which has now been released. This work adds the option to the React Native SDK.
Ran on sample app and confirmed with live stream
TP: 69766
> feat: Add shouldUploadEventCommerce Event Support for Android and iOS

- README.md
- android/src/main/java/com/mparticle/react/MParticleModule.java
- ios/RNMParticle/RNMParticle.m
- js/index.js
This PR adds ecommerce `customAttributes` support.
This is a **Breaking Change**
```js
const product = new MParticle.Product('Test product for cart', '1234', 19.99)
const transactionAttributes = new MParticle.TransactionAttributes('Test transaction id')
const customAttributes = {
myCustomAttribute: 'value',
}
const event = MParticle.CommerceEvent.createProductActionEvent(MParticle.ProductActionType.AddToCart, [product], transactionAttributes, customAttributes)
MParticle.logCommerceEvent(event)
```
fixes #21
> feat: add support for custom attributes in ecommerce events

- android/src/main/java/com/mparticle/react/MParticleModule.java
- sample/android/app/build.gradle
- sample/android/app/src/main/java/com/mparticlesample/MainApplication.java
- sample/index.android.js
A public issue was opened indicating that custom attribute instances containing Boolean keys were crashing in the Android layer. I tested and confirmed this was the case and observed a similar crash with Double and Integers. Even though we only accept String values in the native SDKS, since we don't have any way of enforcing this in vanilla JS, it makes sense to handle this case and stringify the values rather than rejecting them 
Added Boolean and number cases to our sample app and smoke tested...test improvements have been a long time coming on this project but it seemed like too big of a lift for this ticket
Public Issue: https://github.com/mParticle/react-native-mparticle/issues/45
Closes https://go.mparticle.com/work/71487
> Fix: Boolean map customAttribute values crash on Android

- android/build.gradle
- sample/android/build.gradle
remove references to deprecated jcenter repository
Current tests are basically useless, but this same commit is included in the branch that adds effective tests. Passing run is [here](https://github.com/mParticle/react-native-mparticle/actions/runs/1262494776)
Closes https://go.mparticle.com/work/72218
> fix: Remove deprecated jcenter references

- ios/RNMParticle/RNMParticle.m
> Fix syntax errors for the latest React Native release

- ios/RNMParticle/RNMParticle.m
Developers are trying to implement a Promotion and Impression eCommerce event tracking in mP React Native and got the following warning, "Invalid commerce event action".
Testing through a sample React Native App
Closes https://go.mparticle.com/work/77049
> Fix: Remove Extra ProductActionType Check

- android/src/main/java/com/mparticle/react/MParticleModule.java
The Burger King team reported that our React Native SDK crashes their Android app when using the function getUserAttributes. After further investigation I was able to reproduce and it seemed the reason is that we were passing an immutable Java map to the success callback when we needed to actually pass either a readable or writable maps. Also, the older implementation even missed logic to handle user attribute lists which is now also included.
Tested the fix on 4 scenarios locally and all worked as expected:
- In case there where no user attributes in which the an empty map is returned.
- In case there were only user attributes and not attributes lists and worked as expected.
- In case there were only user attribute lists and worked as expected.
- In case there were user attributes and …
> fix to Android's getUserAttributes

- js/index.js
This PR closes this feature request Jira ticket (https://mparticle-eng.atlassian.net/browse/PRODRDMP-5034). The KFC SA team reported that our React Native SDK show values 0 for Tax and Shipping. It was confirmed that later that they were using string values whereas the expected value was expected to be numeric. Our web SDK does parse string values to numeric values when testing and they expected the same behavior for the React Native SDK. The code change here does parse string values into numeric and also works in the case the values are already passed in as numeric values
Tested locally on both iOS and Android with both cases when a numeric value is entered and when a string value is entered
> parse string values transaction attributes to numbers

- android/src/main/java/com/mparticle/react/MParticleModule.java
- ios/RNMParticle/RNMParticle.m
- js/index.js
Allow the newly updated uploadInterval to be settable by the React Native SDK
Tested in my own sample app using latest Android and pointing to the corresponding fix branch on the iOS SDK (this needs released before we release the new React Native SDK)
Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-4949
> feat: Allow uploadInterval to be set manually

- android/src/main/java/com/mparticle/react/MParticleModule.java
- ios/RNMParticle/RNMParticle.m
- js/index.js
{provide a thorough description of the changes}
{explain how this has been tested, and what additional testing should be done}
Closes https://go.mparticle.com/work/REPLACEME
> added setLocation function

- README.md
The npm link step is unnecessary and only for local development of npm packages.  Now that this will be released, it is not needed.
Built an iOS and Android app, and logged setLocation successfully.
Closes https://go.mparticle.com/work/SQDSDKS-6226
> docs: Remove npm link from readme

- README.md
Added Static Library installation steps for clients who don't want to use frameworks for all their dependencies.
Confirmed basic functionality while using these installations steps
Closes https://go.mparticle.com/work/SQDSDKS-6231
> fix: Add Static Library Install Steps

- android/src/main/java/com/mparticle/react/MParticleModule.java
When you are using our android react native sdk ("react-native-mparticle": "^2.7.11") the method product.setVariant() is not forwarding the right value to mParticle. We can see in the “Live Stream” the batch containing the null value for this field, despite we have tried to set it to an string/numeric value. This was confirmed to work iOS so the problem laid entirely in the android layer, specifically were we convert the MPProduct json object to the proper android class MPProduct.
Tested in sample App
Closes https://go.mparticle.com/work/SQDSDKS-6497
> fix: Fix setVariant on Product

- js/rokt/rokt-layout-view.ios.tsx
- js/utils/architecture.ts
Load the legacy native view if Fabric components are not enabled.
Tested with RN version `0.76.9` and `0.79.4`
Closes https://go.mparticle.com/work/REPLACEME
> fix: update architecture checks to use isFabricEnabled in RoktLayoutView iOS

- package.json
In new version of RN view class name was not detected automatically. Add the mapping configuration in codegen config
{explain how this has been tested, and what additional testing should be done}
Closes https://go.mparticle.com/work/REPLACEME
> fix: add iOS configuration for RoktNativeLayout in package.json

- android/src/main/java/com/mparticle/react/MParticleModule.kt
Events logged with a custom event name using:
```js
MParticle.logEvent('Test event', MParticle.EventType.Other, { 'Test key': 'Test value' })
```
come through the to mParticle dashboard with an event name of `RNMParticle`:
I believe this was introduced in https://github.com/mParticle/react-native-mparticle/commit/919c83c1ff397d0ed0a622272ad6f3c2df857b2e - the parameter name was changed from `name` to `eventName` between the [java](https://github.com/mParticle/react-native-mparticle/blob/a09018ce0eb1d2b9c9404549d2f3b7eb8fbc2e14/android/src/main/java/com/mparticle/react/MParticleModule.java#L87) and [kotlin](https://github.com/mParticle/react-native-mparticle/blob/919c83c1ff397d0ed0a622272ad6f3c2df857b2e/android/src/main/java/com/mparticle/react/MParticleModule.kt#L66) files, but `name` is …
> fix: use eventName in logEvent for Android
